
module Constant

  TEAM = %w{LOL ASAP
 Crimson Orenji XOR BiA TCM FQM urANUS FOV FISK DIMENSION aAF LOKI SAINTS ORPHEUS DOT MOTU REWARD TLA  NOTV FEVER 2HD IMMERSE SYS CTU P0W4 TOPAZ}

  ACQUISITION = %w{HDTV SDTV PDTV DSR DSRip DVD DVDRip WS}
end
